on: [push]

permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: logseq/publish-spa@v0.2.0
      - run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
